[package]
name = "defining-modules-to-control-scope"
version = "0.1.0"
authors = ["Rick Winfrey <rewinfrey@github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
